services:
  vulnerable-web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./vulnerable-app:/app

  secure-web:
    build:
      context: .
      args:
        APP_DIR: secure-app
    ports:
      - "8081:8081"
    volumes:
      - ./secure-app:/app
