services:
  vulnerable-web:
    build:
      context: .
      args:
        APP_PORT: 8082
    ports:
      - "8082:8082"
    volumes:
      - ./vulnerable-app:/var/www/html

  secure-web:
    build:
      context: .
      args:
        APP_PORT: 8083
    ports:
      - "8083:8083"
    volumes:
      - ./secure-app:/var/www/html
